### ISSUE TITLE
BUG with try_current_local_offset

### ISSUE THREAD

**Issue by lengyijun** [wyhaya/see#24]
```
▶ see start -b 8080
Serving path   : /home/.....
Serving address: http://0.0.0.0:8080
thread 'see' panicked at 'called `Result::unwrap()` on an `Err` value: IndeterminateOffset', src/option/directory.rs:155:82
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'see' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:394:21
thread 'see' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:394:21
```

**Comment by lengyijun** [comment]
I meet this problem both on Ubuntu20.04.2 and manjaro.
